version: '3'

services:
  alist-sync-web:
    image: xjxjin/alist-sync:1.1.1
    container_name: alist-sync-web
    restart: unless-stopped
    ports:
      - "52441:52441"
    volumes:
      - /DATA/AppData/alist-sync-web/data:/app/data
    environment:
      - TZ=Asia/Shanghai 