name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:
    branches:
      - main

# 添加权限配置
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  DOCKER_IMAGE: ${{ github.repository }}
  PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 添加登录阿里云镜像仓库
      - name: Login to Aliyun Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com  # 替换为你的阿里云镜像仓库地址
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Get version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
          # 去掉版本号中的 'v' 前缀
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          # 为阿里云镜像准备标签
          echo "ALIYUN_IMAGE=registry.cn-hangzhou.aliyuncs.com/${{ env.DOCKER_IMAGE }}:${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ startsWith(github.ref, 'refs/tags/') && steps.get_version.outputs.ALIYUN_IMAGE || '' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}

  build-linux:
    needs: docker-build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [386, amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executables
        run: |
          ARCH="${{ matrix.arch }}"
          PLATFORM_DIR="dist/linux-${ARCH}"
          mkdir -p "$PLATFORM_DIR"
          
          # 复制静态文件
          cp -r static templates README.md "$PLATFORM_DIR/"
          
          # 构建可执行文件
          ARCHITECTURE=$([ "$ARCH" = "386" ] && echo "32bit" || echo "64bit")
          
          # Web 版本
          pyinstaller --clean \
            --name "alist-sync-web" \
            --add-data "static:static" \
            --add-data "templates:templates" \
            --target-architecture $ARCHITECTURE \
            alist-sync-web.py
          
          # CLI 版本
          pyinstaller --clean \
            --name "alist-sync" \
            --target-architecture $ARCHITECTURE \
            alist_sync.py
          
          # 复制构建文件并打包
          cp -r dist/alist-sync-web/* "$PLATFORM_DIR/"
          cp -r dist/alist-sync/* "$PLATFORM_DIR/"
          cd "$PLATFORM_DIR"
          zip -r "../../alist-sync-${{ github.ref_name }}-linux-${ARCH}.zip" ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: dist/alist-sync-${{ github.ref_name }}-linux-${{ matrix.arch }}.zip

  build-windows:
    needs: docker-build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [386, amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executables
        run: |
          $Arch = "${{ matrix.arch }}"
          $PlatformDir = "dist\windows-$Arch"
          mkdir -Force $PlatformDir
          
          # 复制静态文件
          Copy-Item -Path "static", "templates", "README.md" -Destination $PlatformDir -Recurse
          
          # 设置架构
          $Architecture = if ($Arch -eq "386") { "32bit" } else { "64bit" }
          
          # Web 版本
          pyinstaller --clean `
            --name "alist-sync-web" `
            --add-data "static;static" `
            --add-data "templates;templates" `
            --windowed `
            --target-architecture $Architecture `
            alist-sync-web.py
          
          # CLI 版本
          pyinstaller --clean `
            --name "alist-sync" `
            --target-architecture $Architecture `
            alist_sync.py
          
          # 复制构建文件并打包
          Copy-Item -Path "dist\alist-sync-web\*" -Destination $PlatformDir -Recurse
          Copy-Item -Path "dist\alist-sync\*" -Destination $PlatformDir -Recurse
          Compress-Archive -Path "$PlatformDir\*" -DestinationPath "dist\alist-sync-${{ github.ref_name }}-windows-$Arch.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}
          path: dist/alist-sync-${{ github.ref_name }}-windows-${{ matrix.arch }}.zip

  build-macos:
    needs: docker-build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executables
        run: |
          ARCH="${{ matrix.arch }}"
          PLATFORM_DIR="dist/darwin-${ARCH}"
          mkdir -p "$PLATFORM_DIR"
          
          # 复制静态文件
          cp -r static templates README.md "$PLATFORM_DIR/"
          
          # Web 版本
          pyinstaller --clean \
            --name "alist-sync-web" \
            --add-data "static:static" \
            --add-data "templates:templates" \
            --target-architecture 64bit \
            alist-sync-web.py
          
          # CLI 版本
          pyinstaller --clean \
            --name "alist-sync" \
            --target-architecture 64bit \
            alist_sync.py
          
          # 复制构建文件并打包
          cp -r dist/alist-sync-web/* "$PLATFORM_DIR/"
          cp -r dist/alist-sync/* "$PLATFORM_DIR/"
          cd "$PLATFORM_DIR"
          zip -r "../../alist-sync-${{ github.ref_name }}-darwin-${ARCH}.zip" ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-${{ matrix.arch }}
          path: dist/alist-sync-${{ github.ref_name }}-darwin-${{ matrix.arch }}.zip

  create-release:
    needs: [build-linux, build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate Release Body
        id: release_body
        run: |
          CONTENT=$(cat RELEASE.md)
          echo "RELEASE_BODY<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CONTENT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ steps.release_body.outputs.RELEASE_BODY }}
          files: artifacts/**/*.zip

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/xjxjin
          dst: gitee/xjxjin
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          clone_style: "https"
          debug: true
          force_update: true
          static_list: "alist-sync-web"
          timeout: '600s'

