name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux]
        arch: [amd64, 386, armv6, armv7, arm64]
        include:
          - arch: amd64
            docker_platform: linux/amd64
            target_name: x86_64
          - arch: 386
            docker_platform: linux/386
            target_name: i686
          - arch: armv6
            docker_platform: linux/arm/v6
            target_name: armv6
          - arch: armv7
            docker_platform: linux/arm/v7
            target_name: armv7
          - arch: arm64
            docker_platform: linux/arm64/v8
            target_name: aarch64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build binary
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ matrix.docker_platform }}
        outputs: type=local,dest=dist
        build-args: |
          TARGET_ARCH=${{ matrix.target_name }}

    - name: Rename artifacts
      run: |
        cd dist
        for f in *; do
          new_name="alist-sync-web-${f#*-}"
          mv "$f" "$new_name"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.platform }}-${{ matrix.arch }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        find artifacts/ -type f -exec cp {} release-assets/ \;

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        body: |
          Multi-platform builds for ${{ github.ref_name }}
          Supported platforms:
          - Linux (386, amd64, armv6, armv7, arm64)
        files: release-assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}