name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux]
        arch: [amd64, 386, armv6, armv7, arm64]
        include:
          - arch: amd64
            docker_platform: linux/amd64
          - arch: 386
            docker_platform: linux/386
          - arch: armv6
            docker_platform: linux/arm/v6
          - arch: armv7
            docker_platform: linux/arm/v7
          - arch: arm64
            docker_platform: linux/arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:master

    - name: Build binary
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: ${{ matrix.docker_platform }}
        outputs: type=local,dest=dist/${{ matrix.arch }}
        build-args: |
          PYTHON_VERSION=3.10

    - name: Fix permissions
      run: |
        sudo chmod -R 755 dist

    - name: Rename artifacts
      run: |
        cd dist/${{ matrix.arch }}
        mv alist-sync-web alist-sync-web-${{ matrix.platform }}-${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.platform }}-${{ matrix.arch }}
        path: dist/${{ matrix.arch }}/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        find artifacts/ -type f -exec cp {} release-assets/ \;

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        body: |
          Multi-platform builds for ${{ github.ref_name }}
          Supported platforms:
          - Linux (386, amd64, armv6, armv7, arm64)
        files: release-assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}