name: Build Executables and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            docker_image: python:3.10-alpine
          - arch: armv6
            platform: linux/arm/v6
            docker_image: arm32v6/python:3.10-alpine
          - arch: armv7
            platform: linux/arm/v7
            docker_image: arm32v7/python:3.10-alpine
          - arch: arm64
            platform: linux/arm64
            docker_image: arm64v8/python:3.10-alpine
          - arch: ppc64le
            platform: linux/ppc64le
            docker_image: ppc64le/python:3.10-alpine
          - arch: s390x
            platform: linux/s390x
            docker_image: s390x/python:3.10-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build executable
        run: |
          docker run --rm --platform ${{ matrix.platform }} \
            -v "$(pwd):/app" ${{ matrix.docker_image }} \
            sh -c "apk add --no-cache gcc musl-dev python3-dev libffi-dev openssl-dev &&
            pip install --no-cache-dir pyinstaller -r /app/requirements.txt &&
            cd /app &&
            pyinstaller --onefile alist-sync-web.py --name alist-sync &&
            mv dist/alist-sync dist/alist-sync-${{ matrix.arch }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alist-sync-${{ matrix.arch }}
          path: dist/alist-sync-${{ matrix.arch }}

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/alist-sync-*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Pre-built Linux executables for multiple architectures
          draft: false
          prerelease: false