name: Build and Release Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.10"
  REQUIREMENTS: "requirements.txt"

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, armv7l, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential \
              zlib1g-dev \
              libncurses5-dev \
              libgdbm-dev \
              libnss3-dev \
              libssl-dev \
              libreadline-dev \
              libffi-dev \
              wget

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Python dependencies
        run: pip install -r ${{ env.REQUIREMENTS }}

      - name: Setup architecture environment
        run: |
          case "${{ matrix.architecture }}" in
            amd64)
              echo "TARGET_ARCH=x86_64" >> $GITHUB_ENV
              ;;
            armv7l)
              echo "TARGET_ARCH=armv7l" >> $GITHUB_ENV
              ;;
            arm64)
              echo "TARGET_ARCH=aarch64" >> $GITHUB_ENV
              ;;
          esac

      - name: Build executable with PyInstaller
        run: |
          pyinstaller \
              --name "alist-sync_${{ env.TARGET_ARCH }}" \
              --onefile \
              --add-data "static:static" \
              --add-data "templates:templates" \
              --distpath ./dist/${{ matrix.architecture }} \
              alist-sync-web.py

      - name: Package artifacts
        run: |
          cd dist/${{ matrix.architecture }}
          tar czvf ../alist-sync_${GITHUB_REF#refs/tags/}_${{ matrix.architecture }}.tar.gz *

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}