name: Build and Release Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.10"  # 默认版本号
  PLATFORMS: "linux/amd64,linux/arm/v7,linux/arm64"

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binaries
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          outputs: type=local,dest=./dist
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}  # 关键：参数传递无额外字符

      - name: Prepare release assets
        run: |
          cd dist
          find . -name 'alist-sync-*' -exec mv {} . \;
          # 架构映射修正
          for f in *; do
            case "$f" in
              *amd64*)   arch="x86_64"  ;;
              *arm64*)   arch="aarch64" ;;
              *arm/v7*)  arch="armv7l"  ;;
            esac
            mv "$f" "alist-sync_${GITHUB_REF#refs/tags/}_${arch}.bin"
          done
          tar -czvf binaries.tar.gz *.bin

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/binaries.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}